### ISSUE TITLE
 Cannot find name 'Node'.

### ISSUE THREAD

**Issue by a5238392** [eternaljust/Msea_HarmonyOS#1]
提示这个，我是哪没整对吗，我是新手

**Comment by eternaljust** [comment]
> 提示这个，我是哪没整对吗，我是新手

应该是 DevEco Studio IDE 开发环境没有正确安装，建议查看官方文档来配置：https://developer.harmonyos.com/cn/docs/documentation/doc-guides/environment_config-0000001052902427

**Comment by willzhanglj** [comment]
> 提示这个，我是哪没整对吗，我是新手

你解决这个问题了吗，我也遇到

**Comment by willzhanglj** [comment]
> > 提示这个，我是哪没整对吗，我是新手
> 
> 应该是 DevEco Studio IDE 开发环境没有正确安装，建议查看官方文档来配置：https://developer.harmonyos.com/cn/docs/documentation/doc-guides/environment_config-0000001052902427

我可以跑起来hello word 但是跑这个项目 cannot find node

**Comment by look0089** [comment]
我也遇到了这个问题,还有
import * as xpath from 'xpath';
import { DOMParser } from '@xmldom/xmldom'
这两个找不到

ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:3:24
 Cannot find module 'xpath' or its corresponding type declarations.

ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:4:27
 Cannot find module '@xmldom/xmldom' or its corresponding type declarations.

ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:31:84
 Cannot find name 'Node'.

ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:32:72
 Cannot find name 'Node'.

ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:33:81
 Cannot find name 'Node'.

**Comment by eternaljust** [comment]
> 我也遇到了这个问题,还有 import * as xpath from 'xpath'; import { DOMParser } from '@xmldom/xmldom' 这两个找不到
> 
> ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:3:24 Cannot find module 'xpath' or its corresponding type declarations.
> 
> ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:4:27 Cannot find module '@xmldom/xmldom' or its corresponding type declarations.
> 
> ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:31:84 Cannot find name 'Node'.
> 
> ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:32:72 Cannot find name 'Node'.
> 
> ERROR: ArkTS:ERROR File: D:/Harmony/Msea_HarmonyOS-main/entry/src/main/ets/viewmodel/LoginViewModel.ets:33:81 Cannot find name 'Node'.

看你贴出详细的错误日志信息描述是 Windows 开发环境编译报错的，我当前使用的是 macOS 开发环境正常编译成功。猜测大概率是不同的平台开发配置环境不一致导致项目编译失败，我身边暂时只有 macOS 开发电脑，等两天我新购买的 Window 笔记本到了再下载项目测试并修复一下这个问题。

**Comment by eternaljust** [comment]
重新下载项目到 Mac 和 Windows 电脑上编译运行正常（第一次编译报错，第二次后就可以），该问题已修复。
